users:
  page: 10
categories:
  page: 5
mangas:
  limit: 12
  page: 5
  show:
    pages: 5
  truncate: 10
  detail: 100
  most_view: "most_view"
  top_rate: "top_rate"
  finished: "finished"
  not_finished: "not_finished"
  most_followed: "most_followed"
  by_week: "hot_manga_by_time"
  by_month: "hot_manga_by_time"
  view_limit: 100
chapters:
  page: 5
animes:
  page: 5
pages:
  page: 10
